name: BuildWrokflow

on:
  pull_request:
    branches: [ master_v2 ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install criterion
      run: |
        wget -qO- https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 | tar -xjvf -
        sudo cp -a criterion-v2.3.3/lib/. /usr/lib
        sudo cp -a criterion-v2.3.3/include/. /usr/include
    - name: Init
      run: make init
    - name: Clean
      run: make clean_all
    - name: Run unit tests, generate docs
      run: make all
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./doxyConfig"